[phases.setup]
nixPkgs = ["python310", "cairo", "pango", "gdk-pixbuf", "libffi", "gobject-introspection"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "cd app && uvicorn app:app --host 0.0.0.0 --port $PORT"
