[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip", 
  "python310Packages.virtualenv",
  # PDF rendering (weasyprint complete dependencies)
  "cairo",
  "pango",
  "gdk-pixbuf",
  "glib",
  "harfbuzz",
  "fontconfig",
  "freetype",
  "libffi",
  "gobject-introspection",
  # OCR
  "tesseract",
  # PDF tools
  "poppler_utils",
  # Build tools
  "pkg-config",
  "gcc"
]

[phases.setup.nixEnv]
LD_LIBRARY_PATH = "/nix/store/*-glib-*/lib:/nix/store/*-cairo-*/lib:/nix/store/*-pango-*/lib:/nix/store/*-gdk-pixbuf-*/lib:/nix/store/*-gobject-introspection-*/lib:$LD_LIBRARY_PATH"
GI_TYPELIB_PATH = "/nix/store/*-gobject-introspection-*/lib/girepository-1.0"

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  ". /opt/venv/bin/activate && playwright install --with-deps chromium"
]

[start]
cmd = ". /opt/venv/bin/activate && cd app && uvicorn app:app --host 0.0.0.0 --port $PORT"
