[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv", "cairo", "pango", "gdk-pixbuf", "libffi", "gobject-introspection", "glib", "tesseract", "poppler_utils"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  ". /opt/venv/bin/activate && playwright install --with-deps chromium"
]

[start]
cmd = ". /opt/venv/bin/activate && cd app && uvicorn app:app --host 0.0.0.0 --port $PORT"
