[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip", 
  "python310Packages.virtualenv",
  # PDF rendering (weasyprint complete dependencies)
  "cairo",
  "pango",
  "gdk-pixbuf",
  "glib",
  "harfbuzz",
  "fontconfig",
  "freetype",
  "libffi",
  "gobject-introspection",
  # OCR
  "tesseract",
  # PDF tools
  "poppler_utils",
  # Build tools
  "pkg-config",
  "gcc"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  ". /opt/venv/bin/activate && playwright install --with-deps chromium",
  # Create library path setup script
  "echo 'export LD_LIBRARY_PATH=$(find /nix/store -maxdepth 1 -name \"*-glib-*\" -o -name \"*-cairo-*\" -o -name \"*-pango-*\" -o -name \"*-gdk-pixbuf-*\" | xargs -I {} echo {}/lib | tr \"\\n\" \":\" | sed \"s/:$/\"/):$LD_LIBRARY_PATH' > /opt/venv/setup_libs.sh",
  "chmod +x /opt/venv/setup_libs.sh"
]

[start]
cmd = ". /opt/venv/setup_libs.sh && . /opt/venv/bin/activate && cd app && uvicorn app:app --host 0.0.0.0 --port $PORT"
